name = "MyExample"
uuid = "2fc2266b-f6e4-41aa-b223-d8cee0792c4e"
authors = ["Germán Abrevaya"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
